// Center names only — contact/phone/email removed
export const centerData = [
  "Ghatlodiya",
  "Gota",
  "Satellite",
  "Sanand",
  "Vasna",
  "Isanpur",
  "Nikol",
  "Vastral",
  "Naroda",
  "Ghanshyamnagar",
  "Saminarayan dham",
  "Gandhingar Sec. 6",
  "Godhar",
  "Godhra",
  "Himmatnagar",
  "Modasa",
  "Patan",
  "Kadi",
  "Mahesana",
  "Unjha",
  "Vijapur",
  "Morbi",
  "Rajkot",
  "Ankleshwar",
  "Bharuch",
  "Surat - Dabholi",
  "Surat - Varachha",
  "Surendranagar",
  "Vadodara",
  "Bhojnalay",
  "Hospital",
  "Gurukul",
  "Foodstal - Gandhingar",
  "Foodstal - Naroda",
  "Bhakti nivas",
  "Girls Gurukul",
  "Sant-Aasharam",
  "Sahaj Farm",
  "Other",
].map((center) => ({ center }));

// Just the list of center names for simple dropdowns
export const centers = centerData.map(c => c.center);

export const categories = {
  "અનાજ": [
    { name: "ઘઉં", unit: "કિલો" },
    { name: "ચોખા", unit: "કિલો" },
    { name: "બાસમતી ચોખા", unit: "કિલો" },
    { name: "ફાડા ઘઉં", unit: "કિલો" },
    { name: "બાજરી", unit: "કિલો" },
    { name: "ખિચડી", unit: "કિલો" },
    { name: "કણકી", unit: "કિલો" },
    { name: "જુવાર", unit: "કિલો" },
    { name: "મકાઈ", unit: "કિલો" }
  ],
  "કઠોળ": [
    { name: "તુવેરદાળ", unit: "કિલો" },
    { name: "મગદાળ", unit: "કિલો" },
    { name: "મસુરદાળ", unit: "કિલો" },
    { name: "મોગર દાળ", unit: "કિલો" },
    { name: "અડદ દાળ", unit: "કિલો" },
    { name: "ચણા દાળ", unit: "કિલો" },
    { name: "વાલ", unit: "કિલો" },
    { name: "વટાણા", unit: "કિલો" },
    { name: "મગ", unit: "કિલો" },
    { name: "દેશી ચણા", unit: "કિલો" },
    { name: "કાબુલી ચણા", unit: "કિલો" },
    { name: "રાજમા", unit: "કિલો" },
    { name: "ચોળા", unit: "કિલો" },
    { name: "મસુરદાળ", unit: "કિલો" },
    { name: "તુવેર", unit: "કિલો" },
    { name: "સફેદ વટાણા", unit: "કિલો" },
    { name: "લીલા વટાણા", unit: "કિલો" },
    { name: "સફેદ ચોળા", unit: "કિલો" },
    { name: "લાલ ચોળા", unit: "કિલો" },
    { name: "મસુર દાળ", unit: "કિલો" },
    { name: "મસુર", unit: "કિલો" }
  ],
  "ઘી-તેલ": [
    { name: "પામોલિન તેલ", unit: "ડબ્બો" },
    { name: "સનફ્લાવર તેલ", unit: "ડબ્બો" },
    { name: "સોયાબીન તેલ", unit: "ડબ્બો" },
    { name: "ચોખ્ખું ઘી", unit: "ડબ્બો" },
    { name: "ચાલુ ઘી", unit: "ડબ્બો" },
    { name: "દિવેલ", unit: "ડબ્બો" },
    { name: "સીંગતેલ", unit: "ડબ્બો" },
    { name: "કપાસિયા તેલ", unit: "ડબ્બો" },
    { name: "સરસિયું તેલ", unit: "ડબ્બો" }
  ],
  "લોટ": [
    { name: "ગાય છાપ બેસન", unit: "કિલો" },
    { name: "ભગવતી બેસન", unit: "કિલો" },
    { name: "કેપ્ટન બેસન", unit: "કિલો" },
    { name: "આસોપાલવ બેશન", unit: "કિલો" },
    { name: "મેંદો", unit: "કિલો" },
    { name: "સોજી", unit: "કિલો" },
    { name: "આરાનો લોટ", unit: "કિલો" },
    { name: "કકરો લોટ", unit: "કિલો" }
  ],
  "ડ્રાયફ્રુટ": [
    { name: "કાજુ", unit: "કિલો" },
    { name: "બદામ", unit: "કિલો" },
    { name: "દ્રાક્ષ", unit: "કિલો" },
    { name: "પિસ્તા", unit: "કિલો" },
    { name: "અખરોટ", unit: "કિલો" },
    { name: "ખારેક / ખજૂર", unit: "કિલો" },
    { name: "અંજીર", unit: "કિલો" },
    { name: "જરદાલુ / ટોપરું", unit: "કિલો" },
    { name: "શ્રી ફળ / કેસર", unit: "કિલો" },
    { name: "બદામ કતરણ", unit: "કિલો" },
    { name: "પિસ્તા કતરણ", unit: "કિલો" },
    { name: "ખારેક", unit: "કિલો" },
    { name: "ખજૂર", unit: "કિલો" },
    { name: "જરદાળુ", unit: "કિલો" },
    { name: "ટોપરું", unit: "કિલો" },
    { name: "શ્રીફળ", unit: "કિલો" },
    { name: "કેસર", unit: "કિલો" }
  ],
  "ફરાળી": [
    { name: "બટાકા કાતરી", unit: "કિલો" },
    { name: "વેફર", unit: "કિલો" },
    { name: "મોરૈયો", unit: "કિલો" },
    { name: "રાજગરો", unit: "કિલો" },
    { name: "ટોપરાનું છીણ", unit: "કિલો" },
    { name: "સાબુદાણા", unit: "કિલો" },
    { name: "સિંગોડાનો લોટ", unit: "કિલો" }
  ],
  "કલર": [
    { name: "લીલો", unit: "ગ્રામ" },
    { name: "કેસરી", unit: "ગ્રામ" },
    { name: "પીળો", unit: "ગ્રામ" },
    { name: "ગુલાબી", unit: "ગ્રામ" },
    { name: "લાલ", unit: "ગ્રામ" },
    { name: "રાસબરી", unit: "ગ્રામ" },
    { name: "કોફી", unit: "ગ્રામ" }
  ],
  "મસાલા": [
    { name: "ખસખસ", unit: "કિલો" },
    { name: "જાવંત્રી", unit: "કિલો" },
    { name: "મીઠું", unit: "કિલો" },
    { name: "મરચું", unit: "કિલો" },
    { name: "સફેદ મરચું", unit: "કિલો" },
    { name: "લોગી મરચું", unit: "કિલો" },
    { name: "કાશ્મીરી મરચું", unit: "કિલો" },
    { name: "સૂકા મરચાં", unit: "કિલો" },
    { name: "તજ", unit: "કિલો" },
    { name: "લવિંગ", unit: "કિલો" },
    { name: "ઈલાયચી", unit: "કિલો" },
    { name: "ચારોળી", unit: "કિલો" },
    { name: "મગજતરી", unit: "કિલો" },
    { name: "સંચાર", unit: "કિલો" },
    { name: "હળદર", unit: "કિલો" },
    { name: "રાઈ", unit: "કિલો" },
    { name: "રાઈના કુરિયા", unit: "કિલો" },
    { name: "જીરું", unit: "કિલો" },
    { name: "ઘાણા", unit: "કિલો" },
    { name: "ઘાણાજીરું", unit: "કિલો" },
    { name: "મેથી", unit: "કિલો" },
    { name: "મેથી કુરીયા", unit: "કિલો" },
    { name: "ધાણા", unit: "કિલો" },
    { name: "ધાણા કુરીયા", unit: "કિલો" },
    { name: "ધાણા જીરુ", unit: "કિલો" },
    { name: "સફેદ તલ", unit: "કિલો" },
    { name: "કાળા તલ", unit: "કિલો" },
    { name: "ટાટા સોડા", unit: "કિલો" },
    { name: "ટાટા શક્તિ", unit: "કિલો" },
    { name: "દૂધ પાવડર", unit: "કિલો" },
    { name: "નાયલોન પૌઆ", unit: "કિલો" },
    { name: "અજમો", unit: "કિલો" },
    { name: "તલ - કાળા / સફેદ", unit: "કિલો" },
    { name: "વળીયારી", unit: "કિલો" },
    { name: "જાયફળ પાવડર", unit: "કિલો" },
    { name: "લીંબુના ફૂલ", unit: "કિલો" },
    { name: "સાજીના ફૂલ", unit: "કિલો" },
    { name: "ટાટા સોડા / શક્તિ", unit: "કિલો" },
    { name: "કોકમ", unit: "કિલો" },
    { name: "તમાલપત્ર", unit: "કિલો" },
    { name: "બાદીયા પાવડર", unit: "કિલો" },
    { name: "આંબલી", unit: "કિલો" },
    { name: "પાપડ ખારો", unit: "કિલો" },
    { name: "કાળા મરી", unit: "કિલો" },
    { name: "સવા", unit: "કિલો" },
    { name: "સિંગદાણા", unit: "કિલો" },
    { name: "આમચૂર પાવડર", unit: "કિલો" },
    { name: "ગરમ મસાલો", unit: "કિલો" },
    { name: "સૂંઠ પાવડર", unit: "કિલો" },
    { name: "ગંઠોડા પાવડર", unit: "કિલો" },
    { name: "ગુંદર", unit: "કિલો" },
    { name: "દૂધનો મસાલો", unit: "કિલો" },
    { name: "ખાંડ", unit: "કિલો" },
    { name: "બૂરું ખાંડ", unit: "કિલો" },
    { name: "દરેલી ખાંડ", unit: "કિલો" },
    { name: "ગોળ", unit: "કિલો" },
    { name: "સાકર", unit: "કિલો" },
    { name: "દૂધનો પાવડર", unit: "કિલો" },
    { name: "કસ્ટર્ડ પાવડર", unit: "કિલો" },
    { name: "પૌવા", unit: "કિલો" },
    { name: "મકાઇ પૌવા", unit: "કિલો" },
    { name: "હાજીખાની પૌવા", unit: "કિલો" },
    { name: "વિનેગર", unit: "લીટર" }
  ],
  "અન્ય": [
    { name: "મગસની લાડુડી", unit: "કિલો" },
    { name: "મગસના લાડુ", unit: "કિલો" }
  ]
};